<a href="https://colab.research.google.com/github/Jonathan-code-hub/MAT-422-Math-Methods-in-Data-Science/blob/main/homework_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Spaces

In [ ]:
import numpy as np

class Vector:
    def __init__(self, coordinates):
        self.coordinates = np.array(coordinates)

    def __add__(self, other):
        return Vector(self.coordinates + other.coordinates)

    def __mul__(self, scalar):
        return Vector(self.coordinates * scalar)

    def __neg__(self):
        return Vector(-self.coordinates)

    def is_zero(self):
        return np.all(self.coordinates == 0)

    def __repr__(self):
        return f"Vector({self.coordinates})"

# Define vectors #
v1 = Vector([1, 2])
v2 = Vector([3, 4])
v3 = Vector([-1, -2])

# Check closure under addition #
v_add = v1 + v2
print(f"v1 + v2 = {v_add}")

# Check closure under scalar multiplication #
scalar = 2
v_scalar_mult = v1 * scalar
print(f"{scalar} * v1 = {v_scalar_mult}")

# Check the existence of the zero vector #
zero_vector = Vector([0, 0])
print(f"Is {zero_vector} a zero vector? {zero_vector.is_zero()}")

# Check additive inverse #
v_inverse = -v1
v_sum = v1 + v_inverse
print(f"v1 + (-v1) = {v_sum} (Should be zero vector)")

# Demonstrate linear combinations (span) #
# Any linear combination of vectors v1 and v3 should still be in the space #

linear_combination = v1 * 2 + v3 * 3
print(f"2 * v1 + 3 * v3 = {linear_combination}")

v1 + v2 = Vector([4 6])
2 * v1 = Vector([2 4])
Is Vector([0 0]) a zero vector? True
v1 + (-v1) = Vector([0 0]) (Should be zero vector)
2 * v1 + 3 * v3 = Vector([-1 -2])


Orthogonality

In [ ]:
def is_orthogonal(vectors, tol=1e-10):
    """
    Checks if a set of vectors is orthogonal.

    Args:
    vectors -- List of vectors to check for orthogonality.
    tol (float) -- Tolerance for considering dot products as zero (to handle floating-point precision).

    Returns:
    bool -- True if the vectors are orthogonal, false if not
    """
    # Number of vectors #
    num_vectors = len(vectors)

    # Check each pair of distinct vectors #
    for i in range(num_vectors):
        for j in range(i + 1, num_vectors):
            dot_product = np.dot(vectors[i], vectors[j])
            if abs(dot_product) > tol:  # If the dot product is not close to zero #
                return False

    return True

# Example #
vectors = [np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1])]
result = is_orthogonal(vectors)

if result:
    print("The set of vectors is orthogonal.")
else:
    print("The set of vectors is not orthogonal.")

Gram–Schmidt process

In [ ]:
import numpy as np

def gram_schmidt(vectors):
    """
    Orthonormalizes a set of vectors using the Gram-Schmidt process.

    vectors - List of vectors to orthonormalize.

    np.ndarray -- Orthonormalized set of vectors.
    """
    # Ensure the input is a numpy array #
    vectors = np.array(vectors, dtype=float)

    # Number of vectors #
    num_vectors = vectors.shape[0]

    # Initialize an empty array to hold the orthonormal vectors #
    orthonormal_basis = np.zeros_like(vectors)

    for i in range(num_vectors):
        # Start with the current vector #
        vi = vectors[i]

        # Subtract the projection of vi onto all previously computed orthonormal vectors #
        for j in range(i):
            vj = orthonormal_basis[j]
            projection = np.dot(vi, vj) * vj
            vi -= projection

        # Normalize the vector #
        norm = np.linalg.norm(vi)
        if norm > 1e-10:  # Avoid division by zero for nearly zero vectors #
            orthonormal_basis[i] = vi / norm

    return orthonormal_basis

# Example #
vectors = [np.array([1, 1, 1]), np.array([1, 0, 0]), np.array([0, 1, 0])]
orthonormal_vectors = gram_schmidt(vectors)

print("Orthonormal basis:")
print(orthonormal_vectors)

Orthonormal basis:
[[ 5.77350269e-01  5.77350269e-01  5.77350269e-01]
 [ 8.16496581e-01 -4.08248290e-01 -4.08248290e-01]
 [-3.92523115e-16  7.07106781e-01 -7.07106781e-01]]


Eigenvalues and Eigenvectors

In [ ]:
import numpy as np

def eigenvalues(matrix):
    """
    Computes the eigenvalues of a given matrix.

    matrix -- A square matrix (2D array).

    np.ndarray -- The eigenvalues of the matrix.
    """
    # Ensure the input is a numpy array #
    matrix = np.array(matrix)

    # Check if the matrix is square #
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("The input matrix must be square (n x n).")

    # Compute the eigenvalues using numpy's linalg.eigvals function #
    eigenvalues = np.linalg.eigvals(matrix)

    return eigenvalues

# Example #
matrix = np.array([[4, -2],
                   [1,  1]])
eigenvalues = eigenvalues(matrix)

print("Eigenvalues of the matrix:")
print(eigenvalues)

Eigenvalues of the matrix:
[3. 2.]


In [ ]:
import numpy as np

def eigenvalues_and_eigenvectors(matrix):
    """
    Computes the eigenvalues and eigenvectors of a given matrix.

    matrix -- A square matrix (2D numpy array).

    tuple -- A tuple containing a numpy array of eigenvalues and a numpy array of the corresponding eigenvectors.
    """
    # Ensure the input is a numpy array #
    matrix = np.array(matrix)

    # Check if the matrix is square #
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("The input matrix must be square (n x n).")

    # Compute the eigenvalues and eigenvectors using numpy's linalg.eig function #
    eigenvalues, eigenvectors = np.linalg.eig(matrix)

    return eigenvalues, eigenvectors

# Example usage #
matrix = np.array([[3, -1],
                   [1,  2]])
eigenvalues, eigenvectors = eigenvalues_and_eigenvectors(matrix)

print("Eigenvalues of the matrix:")
print(eigenvalues)
print("Eigenvectors of the matrix:")
print(eigenvectors)

Eigenvalues of the matrix:
[2.5+0.8660254j 2.5-0.8660254j]
Eigenvectors of the matrix:
[[-0.70710678+0.j         -0.70710678-0.j        ]
 [-0.35355339+0.61237244j -0.35355339-0.61237244j]]
